# Carmen Catalin Delgado Manzano
name: Hello Catalina Delgado 

on: 
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello 
        run: echo "Hello World"
        
      - name: Fecha hoy
        run: date
        
      - name: Usuario actual
        run: whoami

      - name: Mostrar directorio actual
        run: pwd
        
        
        
