# Catalina

name: First pull_catalina

on:
  push:

jobs:
  Tarea1:
    runs-on: ubuntu-24.04

    steps:
      - name: Say Ayy
        run: |
          echo "Mi primer pull"
          echo "Mi nombre es Carmen Catalina Delgado Manzano"
